In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv("18-concrete_data.csv")

In [3]:
df.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [4]:
df.shape

(1030, 9)

In [5]:
df.columns

Index(['Cement', 'Blast Furnace Slag', 'Fly Ash', 'Water', 'Superplasticizer',
       'Coarse Aggregate', 'Fine Aggregate', 'Age', 'Strength'],
      dtype='object')

In [13]:
df["Blast_Furnace_Slag"] = df.drop(["Blast Furnace Slag"],axis=1)
df["Fine_Aggregate"] = df["Fine Aggregate"]
df["Coarse_Aggregate"] = df["Coarse Aggregate"]

ValueError: Columns must be same length as key

In [9]:
df.columns

Index(['Cement', 'Blast Furnace Slag', 'Fly Ash', 'Water', 'Superplasticizer',
       'Coarse Aggregate', 'Fine Aggregate', 'Age', 'Strength',
       'Blast_Furnace_Slag', 'Fine_Aggregate', 'Coarse_Aggregate'],
      dtype='object')

In [10]:
df.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength,Blast_Furnace_Slag,Fine_Aggregate,Coarse_Aggregate
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99,0.0,676.0,1040.0
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89,0.0,676.0,1055.0
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27,142.5,594.0,932.0
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05,142.5,594.0,932.0
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30,132.4,825.5,978.4