In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv("binance_btc_4h_2018_2026_features.csv")

In [3]:
df.tail()

,Timestamp,Open,High,Low,Close,Volume,volume_adi,volume_obv,volume_cmf,volume_fi,...,momentum_ppo,momentum_ppo_signal,momentum_ppo_hist,momentum_pvo,momentum_pvo_signal,momentum_pvo_hist,momentum_kama,others_dr,others_dlr,others_cr
17941,2026-03-12 20:00:00,70432.33,70734.25,70013.17,70541.34,2336.09458,1.009022e+07,3.056228e+06,-0.017325,6.367575e+05,...,0.610608,0.563296,0.047312,-4.560486,-0.322812,-4.237674,69581.959132,0.154787,0.154667,426.034170
17942,2026-03-13 00:00:00,70541.34,72000.00,70386.01,71405.75,5755.69452,1.009174e+07,3.061983e+06,-0.012415,1.256546e+06,...,0.714215,0.593480,0.120736,-0.980313,-0.454312,-0.526001,69797.870418,1.225395,1.217948,432.480166
17943,2026-03-13 04:00:00,71405.76,71672.76,71180.19,71612.22,4181.63698,1.009489e+07,3.066165e+06,0.049754,1.200380e+06,...,0.810169,0.636817,0.173351,-1.144972,-0.592444,-0.552528,69935.050524,0.289150,0.288733,434.019834
17944,2026-03-13 08:00:00,71612.23,72575.98,71385.28,72228.82,5105.15070,1.009702e+07,3.071270e+06,0.076027,1.478588e+06,...,0.945226,0.698499,0.246727,0.433384,-0.387278,0.820662,70133.367070,0.861026,0.857341,438.617885
17945,2026-03-13 12:00:00,72228.81,73593.00,72210.00,73328.73,4917.15418,1.010006e+07,3.076187e+06,0.069111,2.039994e+06,...,1.163006,0.791401,0.371606,1.300904,-0.049642,1.350546,70800.517828,1.522813,1.511335,446.820029

In [4]:
df.describe()

,Open,High,Low,Close,Volume,volume_adi,volume_obv,volume_cmf,volume_fi,volume_em,...,momentum_ppo,momentum_ppo_signal,momentum_ppo_hist,momentum_pvo,momentum_pvo_signal,momentum_pvo_hist,momentum_kama,others_dr,others_dlr,others_cr
count,17946.000000,17946.000000,17946.000000,17946.000000,17946.000000,1.794600e+04,1.794600e+04,17946.000000,1.794600e+04,1.794600e+04,...,17946.000000,17946.000000,17946.000000,17946.000000,17946.000000,17946.000000,17946.000000,17946.000000,17946.000000,17946.000000
mean,38246.054084,38560.447053,37910.445938,38249.396376,10713.225323,5.403734e+06,1.523420e+06,0.042846,-8.769303e+04,2.068610e+06,...,0.042634,0.042458,0.000176,-1.371968,-1.371957,-0.000011,38251.598862,0.019184,0.009467,185.229760
std,32485.244129,32688.635174,32268.905198,32485.782235,14368.862866,3.702966e+06,1.405837e+06,0.127283,3.669183e+06,1.292617e+10,...,1.593816,1.507863,0.461715,12.487537,9.882487,6.827888,32483.276584,1.392070,1.395364,242.249885
min,3172.620000,3210.000000,3156.260000,3172.050000,5.887034,-7.245532e+03,-9.172363e+05,-0.407458,-6.251811e+07,-6.654058e+11,...,-11.814582,-10.322847,-3.988297,-50.715853,-45.670440,-17.731704,3246.287732,-20.496236,-22.936582,-76.345691
25%,9548.630000,9630.747500,9459.947500,9548.502500,3659.548032,1.248562e+06,-3.672053e+03,-0.044884,-5.306896e+05,-4.632543e+08,...,-0.688091,-0.651313,-0.228206,-9.236627,-7.646063,-4.599729,9600.709429,-0.470950,-0.472062,-28.795816
50%,28127.635000,28374.145000,27908.885000,28134.410000,6257.523531,5.535495e+06,1.712035e+06,0.041658,-6.589064e+03,5.126519e+06,...,0.046090,0.047809,-0.005452,-1.800241,-1.549046,-0.686334,28131.222590,0.019369,0.019367,109.801246
75%,59414.880000,59932.282500,58866.500000,59416.972500,11361.605046,9.260156e+06,3.058933e+06,0.126877,4.952246e+05,6.559702e+08,...,0.854289,0.827565,0.222171,6.007576,4.751636,3.805859,59273.239605,0.513637,0.512322,343.078595
max,125410.800000,126199.630000,124800.000000,125410.810000,284711.694213,1.011630e+07,3.422245e+06,0.521882,7.245077e+07,1.756758e+11,...,6.341956,5.502219,3.008708,59.658646,36.224820,44.601687,123121.777258,14.749019,13.757711,835.201562

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17946 entries, 0 to 17945
Data columns (total 92 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Timestamp                  17946 non-null  object
 1   Open                       17946 non-null  float64
 2   High                       17946 non-null  float64
 3   Low                        17946 non-null  float64
 4   Close                      17946 non-null  float64
 5   Volume                     17946 non-null  float64
 6   volume_adi                 17946 non-null  float64
 7   volume_obv                 17946 non-null  float64
 8   volume_cmf                 17946 non-null  float64
 9   volume_fi                  17946 non-null  float64
 10  volume_em                  17946 non-null  float64
 11  volume_sma_em              17946 non-null  float64
 12  volume_vpt                 17946 non-null  float64
 13  volume_vwap                17946 non-null  float64
 14  volume_mfi                 17946 non-null  float64
 15  volume_nvi                 17946 non-null  float64
 16  volatility_bbm             17946 non-null  float64
 17  volatility_bbh             17946 non-null  float64
 18  volatility_bbl             17946 non-null  float64
 19  volatility_bbw             17946 non-null  float64
 20  volatility_bbp             17946 non-null  float64
 21  volatility_bbhi            17946 non-null  float64
 22  volatility_bbli            17946 non-null  float64
 23  volatility_kcc             17946 non-null  float64
 24  volatility_kch             17946 non-null  float64
 25  volatility_kcl             17946 non-null  float64
 26  volatility_kcw             17946 non-null  float64
 27  volatility_kcp             17946 non-null  float64
 28  volatility_kchi            17946 non-null  float64
 29  volatility_kcli            17946 non-null  float64
 30  volatility_dcl             17946 non-null  float64
 31  volatility_dch             17946 non-null  float64
 32  volatility_dcm             17946 non-null  float64
 33  volatility_dcw             17946 non-null  float64
 34  volatility_dcp             17946 non-null  float64
 35  volatility_atr             17946 non-null  float64
 36  volatility_ui              17946 non-null  float64
 37  trend_macd                 17946 non-null  float64
 38  trend_macd_signal          17946 non-null  float64
 39  trend_macd_diff            17946 non-null  float64
 40  trend_sma_fast             17946 non-null  float64
 41  trend_sma_slow             17946 non-null  float64
 42  trend_ema_fast             17946 non-null  float64
 43  trend_ema_slow             17946 non-null  float64
 44  trend_vortex_ind_pos       17946 non-null  float64
 45  trend_vortex_ind_neg       17946 non-null  float64
 46  trend_vortex_ind_diff      17946 non-null  float64
 47  trend_trix                 17946 non-null  float64
 48  trend_mass_index           17946 non-null  float64
 49  trend_dpo                  17946 non-null  float64
 50  trend_kst                  17946 non-null  float64
 51  trend_kst_sig              17946 non-null  float64
 52  trend_kst_diff             17946 non-null  float64
 53  trend_ichimoku_conv        17946 non-null  float64
 54  trend_ichimoku_base        17946 non-null  float64
 55  trend_ichimoku_a           17946 non-null  float64
 56  trend_ichimoku_b           17946 non-null  float64
 57  trend_stc                  17946 non-null  float64
 58  trend_adx                  17946 non-null  float64
 59  trend_adx_pos              17946 non-null  float64
 60  trend_adx_neg              17946 non-null  float64
 61  trend_cci                  17946 non-null  float64
 62  trend_visual_ichimoku_a    17946 non-null  float64
 63  trend_visual_ichimoku_b    17946 non-null  float64
 64  trend_aroon_up             17946 non-null  float64
 65  trend_aroon_down           17946 non-null  float64
 66  trend_aroon_ind            17946 non-null  float64
 67  trend_psar_up              17946 non-null  float64
 68  trend_psar_down            17946 non-null  float64
 69  trend_psar_up_indicator    17946 non-null  float64
 70  trend_psar_down_indicator  17946 non-null  float64
 71  momentum_rsi               17946 non-null  float64
 72  momentum_stoch_rsi         17946 non-null  float64
 73  momentum_stoch_rsi_k       17946 non-null  float64
 74  momentum_stoch_rsi_d       17946 non-null  float64
 75  momentum_tsi               17946 non-null  float64
 76  momentum_uo                17946 non-null  float64
 77  momentum_stoch             17946 non-null  float64
 78  momentum_stoch_signal      17946 non-null  float64
 79  momentum_wr                17946 non-null  float64
 80  momentum_ao                17946 non-null  float64
 81  momentum_roc               17946 non-null  float64
 82  momentum_ppo               17946 non-null  float64
 83  momentum_ppo_signal        17946 non-null  float64
 84  momentum_ppo_hist          17946 non-null  float64
 85  momentum_pvo               17946 non-null  float64
 86  momentum_pvo_signal        17946 non-null  float64
 87  momentum_pvo_hist          17946 non-null  float64
 88  momentum_kama              17946 non-null  float64
 89  others_dr                  17946 non-null  float64
 90  others_dlr                 17946 non-null  float64
 91  others_cr                  17946 non-null  float64
dtypes: float64(91), object(1)
memory usage: 12.6+ MB

In [9]:
df[df.corr(numeric_only=True)]

,Timestamp,Open,High,Low,Close,Volume,volume_adi,volume_obv,volume_cmf,volume_fi,...,momentum_ppo,momentum_ppo_signal,momentum_ppo_hist,momentum_pvo,momentum_pvo_signal,momentum_pvo_hist,momentum_kama,others_dr,others_dlr,others_cr
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17941,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17943,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17944,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17945,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
# istatiksel filtreleme (korelasyon matrisi) -> tahmin edilmesi istenen değer ile diğer değişkenlerin bağlantısı 
# en yüksek olanları seçer diğerlerini drop ederiz.

# algoritmik puanlama (Tree-based feature importance) -> korelasyon her zaman tahmin edilmesi istenen değer 
# ile diğer değişkenlerin bağlantısını doğru bulamayabilir.
# ham veri setini LightGBM veya Random Forest içerisine veririz.

# 1.ilk sırada EDA yapılarak modele vermeden önce elimizde ne olduğuna bakılmalı

# 2. Data cleaning & preprocessing yapılmalı  ( preprocessing değerler arasındaki devasa farkları sayıları küçülterek
# önem sırasına koymaya yarar.

# 3. Feature Engineering yapılmalı 

# 4. Feature Selection yapılmalı ( birbirinin kopyası olan satırlardan birisi silinir, hedef değişkenle 
# en alakalı satırlar bırakılır. korelasyonu 0.9 veya -0.9 üzeri olanlardan silinecekler arasında
# hedef değişkenle en alakalı olan bırakılır diğer satır silinir.)

# Train test split

# Model Training & Hyperparameter Tuning 

# Backtesting & Evaluation(modelin hiç görmediği test verisiyle sonuclara bakılır)