In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import load_breast_cancer

In [3]:
data = load_breast_cancer(as_frame=True)

In [4]:
df = data.frame

In [5]:
df.tail()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,0
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,0
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,0
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,1

In [6]:
df.shape

(569, 31)

In [7]:
data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [8]:
X = df.drop("target", axis=1)
y = df["target"]

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=15)

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
columns = data.feature_names

In [16]:
X_train = pd.DataFrame(X_train, columns = columns)

In [17]:
X_train

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,0.083873,-0.983504,0.077016,-0.048605,0.221698,-0.051884,-0.060168,0.161591,-0.346668,-0.305506,...,-0.085581,-0.966340,0.034735,-0.201125,-0.048765,0.127497,0.181973,0.692247,-0.352364,-0.410313
1,-0.098493,-0.836530,-0.147500,-0.197898,-0.613975,-0.716869,-0.975662,-1.003775,-1.492869,-0.633109,...,-0.203450,-1.357382,-0.277513,-0.305135,-1.140546,-0.953456,-1.143545,-1.241889,-1.650695,-0.909548
2,-0.109546,-0.325735,-0.157523,-0.200377,-1.246710,-0.781996,-0.750730,-0.917676,-1.248538,-1.009923,...,-0.189225,-0.532034,-0.298232,-0.271845,-1.592025,-0.464299,-0.559484,-0.828913,-0.884492,-0.792888
3,-0.267045,-0.145029,-0.243320,-0.339202,1.388597,0.348021,0.404600,0.625858,1.104948,0.673085,...,-0.122161,0.381507,-0.134521,-0.214061,2.054257,1.057091,1.098798,1.438258,1.534273,1.938320
4,0.680711,2.124638,0.651537,0.551871,-0.876346,-0.048075,0.033943,0.102530,-0.828144,-0.914314,...,0.550504,1.408201,0.562929,0.414834,-0.840754,0.360708,0.326507,0.416116,-1.090477,-0.331968
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,1.194654,-0.178760,1.164716,1.149318,0.152119,0.009054,0.538869,0.999480,1.119321,-0.388462,...,1.353231,0.336579,1.307070,1.241056,0.318145,-0.292152,0.207989,0.757847,1.214372,0.102075
422,0.086637,0.230840,0.097864,-0.041443,0.150670,0.300413,0.347936,0.276631,0.465375,0.235812,...,0.418409,0.742597,0.306127,0.276842,1.007221,0.985634,1.080009,1.056862,2.865374,0.989031
423,0.979129,0.356129,1.016375,0.842744,1.076941,1.174491,1.179419,1.447569,0.540830,-0.185994,...,0.853305,-0.091071,0.743857,0.721864,0.407636,0.623151,0.413227,0.564098,-0.708156,-0.378861
424,-0.236650,-1.335278,-0.250937,-0.319370,-0.943026,-0.363239,-0.480221,-0.523511,-0.731130,-0.990239,...,-0.412769,-1.379014,-0.315741,-0.448129,-0.719942,0.095017,0.067792,-0.347744,-0.282142,-0.617899
425,-0.692567,2.416177,-0.688743,-0.668363,-0.222593,-0.363429,-0.223632,-0.741008,-0.077184,-0.185994,...,-0.640378,2.188621,-0.623611,-0.613546,0.353941,-0.329829,0.095253,-0.704425,-0.051189,-0.675085

In [18]:
X_test = pd.DataFrame(X_test, columns = columns)

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier

In [20]:
logistic = LogisticRegression()
gbc = GradientBoostingClassifier()

In [21]:
logistic.fit(X_train, y_train)
gbc.fit(X_train, y_train)

GradientBoostingClassifier()

In [22]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [24]:
print("log")

y_pred_log = logistic.predict(X_test)
print(accuracy_score(y_test, y_pred_log))
print(confusion_matrix(y_test, y_pred_log))
print(classification_report(y_test, y_pred_log))

print("------------")
y_pred_gbc = gbc.predict(X_test)
print(accuracy_score(y_test, y_pred_gbc))
print(confusion_matrix(y_test, y_pred_gbc))
print(classification_report(y_test, y_pred_gbc))

log
0.958041958041958
[[49  4]
 [ 2 88]]
              precision    recall  f1-score   support

           0       0.96      0.92      0.94        53
           1       0.96      0.98      0.97        90

    accuracy                           0.96       143
   macro avg       0.96      0.95      0.95       143
weighted avg       0.96      0.96      0.96       143

------------
0.951048951048951
[[47  6]
 [ 1 89]]
              precision    recall  f1-score   support

           0       0.98      0.89      0.93        53
           1       0.94      0.99      0.96        90

    accuracy                           0.95       143
   macro avg       0.96      0.94      0.95       143
weighted avg       0.95      0.95      0.95       143

In [25]:
from sklearn.decomposition import PCA

In [48]:
pca = PCA(n_components=2)

In [49]:
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

In [50]:
X_train_pca = pd.DataFrame(X_train_pca, columns = ["PCA 1", "PCA 2"])

In [51]:
X_test_pca = pd.DataFrame(X_test_pca, columns = ["PCA 1", "PCA 2"])

In [52]:
X_train_pca

        PCA 1     PCA 2
0   -0.478413 -0.480238
1   -3.476482 -2.219422
2   -3.054738 -2.309091
3    1.628649  2.254628
4    1.231041 -1.899407
..        ...       ...
421  3.158756 -1.599216
422  1.182785  0.278223
423  3.986776 -0.321750
424 -2.341799 -1.050465
425 -1.264204  0.782168

[426 rows x 2 columns]

In [53]:
log = LogisticRegression()
gbc = GradientBoostingClassifier()

In [54]:
log.fit(X_train_pca, y_train)
gbc.fit(X_train_pca, y_train)

GradientBoostingClassifier()

In [55]:
print("log")

y_pred_log = logistic.predict(X_test_pca)
print(accuracy_score(y_test, y_pred_log))
print(confusion_matrix(y_test, y_pred_log))
print(classification_report(y_test, y_pred_log))

print("------------")
y_pred_gbc = gbc.predict(X_test_pca)
print(accuracy_score(y_test, y_pred_gbc))
print(confusion_matrix(y_test, y_pred_gbc))
print(classification_report(y_test, y_pred_gbc))

log

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- PCA 1
- PCA 2
Feature names seen at fit time, yet now missing:
- area error
- compactness error
- concave points error
- concavity error
- fractal dimension error
- ...